### PR TITLE
Add an Indexer section within Developer Tools

### PR DESCRIPTION
**Pull request by seandotau**
## Proposed changes

Propose to add an Indexer section the Developer Tools and have SubQuery as one of the child pages. 

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Minor Issues and Typos
- [ ] Major Content Contribution
- [x] Minor Content Contribution
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn-docs/blob/master/CONTRIBUTING.md)
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn-docs)
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Related issues
NA

## Further comments
NA

### CODE REVIEW

**Comment by ayo-klaytn** [comment]
@Sean thanks for raising this PR to add the SubQuery Indexer

I will like for you to do the following: 

- Create an indexer folder in the dapp/developer-tools folder
- Move the subquery.md file into the indexer folder
- For the Indexer content to show in the documentation, link each topic with its file in Summary.md
- The links below should be added beneath the oracle section in summary.md
* [Indexers](dapp/developer-tools/indexers/getting-started.md)
-         * [SubQuery](dapp/developer-tools/indexers/subquery.md)
- Sign the CLA [here](https://github.com/klaytn/klaytn-docs/pull/612#issuecomment-1802877497)
- If you have previously signed the CLA, kindly comment "I have read the CLA Document and I hereby sign the CLA" or “recheck" in the pull request below.

**Comment by ayo-klaytn** [comment]
@Sean thanks for raising this PR to add the SubQuery Indexer

I will like for you to do the following: 

- Create an indexer folder in the dapp/developer-tools folder
- Move the subquery.md file into the indexer folder
- Create a new getting-started.md file in the indexer folder
- For the Indexer content to show in the documentation, link each topic with its file in Summary.md
- The links below should be added beneath the oracle section in summary.md
-     * [Indexers](dapp/developer-tools/indexers/getting-started.md)
-         * [SubQuery](dapp/developer-tools/indexers/subquery.md)
- Sign the CLA [here](https://github.com/klaytn/klaytn-docs/pull/612#issuecomment-1802877497)
- If you have previously signed the CLA, kindly comment "I have read the CLA Document and I hereby sign the CLA" or "recheck" in the pull request below.

**Comment by seandotau** [comment]
Thanks for the feedback @ayo-klaytn . I have actioned the above items. Please check.

**Comment by ayo-klaytn** [comment]
@seandotau Can you comment "I have read the CLA Document and I hereby sign the CLA" in this pull request and re-run the CLA job?

**Review by ayo-klaytn — APPROVED** [review]

**Review by praveen-klaytn — APPROVED** [review]

**Comment by seandotau** [comment]
Hi @ayo-klaytn , Sure. 
I have read the CLA Document and I hereby sign the CLA.

I also signed it at: https://gist.github.com/klaytndocs/8092ceb823571be53f4bc50587fd3d94 :)

**Comment by ayo-klaytn** [comment]
Alright then. If you have signed the CLA, can you both  comment "I have read the CLA Document and I hereby sign the CLA" and  "recheck" in this pull request below?

**Comment by seandotau** [comment]
Hi @ayo-klaytn , 
I thought i did comment "I have read the CLA Document and I hereby sign the CLA" above already? 

I can see "Some checks were not successful" with the CLA part failed and the license/cla = pending. How do I "recheck" the PR? Is there a recheck button I have to click or something? 
Thanks.

**Comment by ayo-klaytn** [comment]
@seandotau oh yes just kindly comment "recheck" directly in this PR

**Comment by seandotau** [comment]
Sure. 
Please recheck.

**Comment by ayo-klaytn** [comment]
@seandotau can you comment: 

1. recheck as an individual comment as it is in this PR directly?

2. I have read the CLA Document and I hereby sign the CLA as an individual comment as it is in this PR directly?

**Comment by seandotau** [comment]
recheck

**Comment by seandotau** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by seandotau** [comment]
Hi @ayo-klaytn , i think I've done what you asked for correctly.... (Terribly confused).

**Comment by seandotau** [comment]
recheck

**Comment by Sotatek-TinnNguyen** [comment]
Hi @seandotau, I see that you had commited with email <you@example.com> that not linked to your account, can you change your email of previous commit to your email: seandotau@gmail.com and recheck the CLA?
I think this command can help you:
`git rebase -i HEAD~6 -x "git commit --amend --author 'seandotau <seandotau@gmail.com>' --no-edit"`

**Comment by ayo-klaytn** [comment]
@seandotau thanks for your patience and contribution 🫡

**Pull request merged**
