### PR TITLE
Update Orakl Network VRF Tutorial

### PR DESCRIPTION
**Pull request by martinkersner**
## Proposed changes

This PR updates Orakl Network VRF tutorial. The previous version was outdated, utilizing old way of VRF requests, and linking to deprecated contracts and key hashes. Additionally, banner image and screenshots are updated as well.

## Types of changes

- [x] Minor Issues and Typos
- [ ] Major Content Contribution
- [ ] Others

## Checklist

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn-docs/blob/master/CONTRIBUTING.md)
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn-docs)
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by martinkersner** [comment]
recheck

**Comment by ayo-klaytn** [comment]
@martinkersner Thanks for the update.
Can you comment, "I have read the CLA document, and I hereby sign the CLA" in the [gist file?](https://gist.github.com/klaytndocs/8092ceb823571be53f4bc50587fd3d94)

**Review by ayo-klaytn — APPROVED** [review]

**Comment by martinkersner** [comment]
@ayo-klaytn Done!

**Comment by ayo-klaytn** [comment]
recheck

**Review by praveen-klaytn — APPROVED** [review]

**Comment by ayo-klaytn** [comment]
@martinkersner You can re-trigger this bot by commenting "recheck" in this Pull Request. So we can re-run the failed checks

Thanks

**Comment by martinkersner** [comment]
recheck

**Comment by Sotatek-HuyTran5** [comment]
Hi @martinkersner , can you comment `I have read the CLA Document and I hereby sign the CLA` in here

**Comment by martinkersner** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
