### PR TITLE
Add DRPC to RPC Service Providers

### PR DESCRIPTION
**Pull request by say-malove**
## Proposed changes

Add DRPC to RPC Service Providers. 
DRPC is a decentralized network of RPC providers. - https://drpc.org/
Privacy policy - https://drpc.org/privacy-policy

## Types of changes

Please put an x in the boxes related to your change.

- [x] Minor Issues and Typos
- [ ] Major Content Contribution
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn-docs/blob/master/CONTRIBUTING.md)
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn-docs)
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

https://docs.klaytn.foundation/content/dapp/rpc-service
https://drpc.org/public-endpoints/klaytn

## Further comments

If this is a relatively large content contribution, kick off the discussion by explaining why you would suggest the content contribution, etc...

### CODE REVIEW

**Review by scott-klaytn — APPROVED** [review]

**Review by kjhman21 — CHANGES_REQUESTED** [review]
https://drpc.org/#networks
@say-malove Can you add Klaytn in this main page too?

**Review by ayo-klaytn — APPROVED** [review]

**Comment by blukat29** [comment]
I've resolved the merge conflict.

**Comment by kjhman21** [comment]
@say-malove Thanks. Now I can see that Klaytn is there!

**Review by kjhman21 — APPROVED** [review]

**Comment by blukat29** [comment]
recheck

**Comment by ayo-klaytn** [comment]
@say-malove, kindly comment "I have read the CLA Document and I hereby sign the CLA" on this [gist file](https://gist.github.com/klaytndocs/8092ceb823571be53f4bc50587fd3d94) and re-run the CLA job.

Thanks

**Comment by ayo-klaytn** [comment]
> @say-malove, kindly comment "I have read the CLA Document and I hereby sign the CLA" on this [gist file](https://gist.github.com/klaytndocs/8092ceb823571be53f4bc50587fd3d94) and re-run the CLA job.
> 
> Thanks

@say-malove can you take a look at this? Thanks 🙏

**Comment by scott-klaytn** [comment]
If applicable, this PR will be reflected to new docs set after docs migration.

**Pull request closed without merging**
