### PR TITLE
Create pipeline to check the links in docs

### PR DESCRIPTION
**Pull request by iv0rish**
## Proposed changes

- When PR opened, this pipeline will check every links in markdown files.
- New issue will created after pipeline finished running - With the result of link coverage. ([Sample issue](https://github.com/iv0rish/klaytn-docs/issues/4))
- Add link coverage badge to README

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Minor Issues and Typos
- [ ] Major Content Contribution
- [x] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn-docs/blob/master/CONTRIBUTING.md)
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn-docs)
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by iv0rish** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by kjhman21 — APPROVED** [review]

**Review by aidan-kwon — APPROVED** [review]

**Comment by aidan-kwon** [comment]
@iv0rish Can you see the CI failure?

**Comment by iv0rish** [comment]
> @iv0rish Can you see the CI failure?

It's normal because pipeline can't runs on forked repository. I've attached a [sample result](https://github.com/iv0rish/klaytn-docs/issues/4) running on forked branch.

**Comment by aidan-kwon** [comment]
@iv0rish If it is good to go, please merge this

**Comment by scott-klaytn** [comment]
No longer applicable due to docs platform change.

**Pull request closed without merging**
