### PR TITLE
caver.ipfs.add(). Buffer as parameter

### PR DESCRIPTION
**Pull request by jing-klaytn**
## Proposed changes

When we use caver.ipfs.add(string | Buffer | ArrayBuffer) and want to pass file contents as buffer,  please use this pattern :     caver.ipfs.add( Buffer.from('xxxxx').buffer )

## Types of changes

Please put an x in the boxes related to your change.

- [x] Minor Issues and Typos
- [ ] Major Content Contribution
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn-docs/blob/master/CONTRIBUTING.md)
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn-docs)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- None

## Further comments

- None

### CODE REVIEW

**Review by kjhman21 — APPROVED** [review]

**Comment by kjhman21** [comment]
@jimni1222 Please take a look.

**Comment by jimni1222** [comment]
@jing-klaytn Hi, thank you for contribution.
But `caver.ipfs.add` should accept both Buffer and ArrayBuffer type.
If you want to add an example for ArrayBuffer, please add separate.

**Comment by kjhman21** [comment]
@jimni1222 
@jing-klaytn said that `caver.ipfs.add(Buffer.from())` does not work. I'm not sure this is true or not. Could you please check it again?

**Comment by jimni1222** [comment]
@kjhman21 I checked yesterday, and that worked.
@jing-klaytn Can you share the example code, and please let me know caver-js and Node.js version also. Thanks.

**Comment by kjhman21** [comment]
@jimni1222 Then, it would be good to close this issue. Thanks.

**Pull request closed without merging**
