### PR TITLE
new gas price

### PR DESCRIPTION
**Pull request by terrikwak**
## Proposed changes

Created this PR with new gas price in advance so that it can be merged as soon as the gas fee is applied

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Minor Issues and Typos
- [ ] Major Content Contribution
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn-docs/blob/master/CONTRIBUTING.md)
- [ ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn-docs)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large content contribution, kick off the discussion by explaining why you would suggest the content contribution, etc...

### CODE REVIEW

**Comment by terrikwak** [comment]
@kjhman21  When should the new gas price be applied on Klaytn Docs, on the 22nd?

**Comment by kjhman21** [comment]
@terrikwak yes.

**Comment by terrikwak** [comment]
@kjhman21 @dcground  @aidan-kwon  Can you approve in advance so I can merge it easily on time?

**Review by aidan-kwon — APPROVED** [review]
Thank you!

**Review by kjhman21 — APPROVED** [review]

**Review by dcground — APPROVED** [review]

**Pull request merged**
